FROM node:10.19.0

LABEL version="1.0"
LABEL description="This is the base docker image for the Skiplog backend API."

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]
RUN ls
RUN npm install --production
COPY . .

EXPOSE 5000

CMD ["node", "app.js"]